-- MySQL Script generated by MySQL Workbench
-- Sat Nov 28 15:06:20 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fiscalizepro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fiscalizepro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fiscalizepro` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fiscalizepro` ;

-- -----------------------------------------------------
-- Table `fiscalizepro`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalizepro`.`Usuario` (
  `usuarioId` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `facebookId` VARCHAR(45) NULL,
  `tokenId` VARCHAR(100) NULL,
  `nome` VARCHAR(100) NULL,
  `email` VARCHAR(200) NULL,
  PRIMARY KEY (`usuarioId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fiscalizepro`.`Fiscalizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalizepro`.`Fiscalizacao` (
  `fiscalizacaoId` INT NOT NULL AUTO_INCREMENT,
  `notaFiscalId` INT NOT NULL,
  `numeroSuspeitas` INT NOT NULL DEFAULT 0,
  `numeroSuspeitasValor` INT NOT NULL DEFAULT 0,
  `numeroSuspeitasObjeto` INT NOT NULL DEFAULT 0,
  `numeroSuspeitasBeneficiario` INT NOT NULL DEFAULT 0,
  `dataAtualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`fiscalizacaoId`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `NotaFiscal` ON `fiscalizepro`.`Fiscalizacao` (`notaFiscalId` ASC);


-- -----------------------------------------------------
-- Table `fiscalizepro`.`Analise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalizepro`.`Analise` (
  `analiseId` INT NOT NULL AUTO_INCREMENT,
  `fiscalizacaoId` INT NOT NULL,
  `usuarioResponsavelId` INT NOT NULL,
  `concluida` TINYINT(1) NOT NULL DEFAULT 0,
  `comentarios` VARCHAR(4000) NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataAtualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`analiseId`),
  CONSTRAINT `fk_Analise_Fiscalizacao`
    FOREIGN KEY (`fiscalizacaoId`)
    REFERENCES `fiscalizepro`.`Fiscalizacao` (`fiscalizacaoId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Analise_Usuario1`
    FOREIGN KEY (`usuarioResponsavelId`)
    REFERENCES `fiscalizepro`.`Usuario` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Analise_Fiscalizacao_idx` ON `fiscalizepro`.`Analise` (`fiscalizacaoId` ASC);

CREATE INDEX `fk_Analise_Usuario1_idx` ON `fiscalizepro`.`Analise` (`usuarioResponsavelId` ASC);


-- -----------------------------------------------------
-- Table `fiscalizepro`.`Anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalizepro`.`Anexo` (
  `anexoId` INT NOT NULL AUTO_INCREMENT,
  `analiseId` INT NOT NULL,
  `url` VARCHAR(4000) NOT NULL,
  `tipo` CHAR(1) NOT NULL COMMENT '\'imagem, video, url\'',
  `dataCriacao` DATETIME NOT NULL,
  PRIMARY KEY (`anexoId`),
  CONSTRAINT `fk_Anexo_Analise1`
    FOREIGN KEY (`analiseId`)
    REFERENCES `fiscalizepro`.`Analise` (`analiseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Anexo_Analise1_idx` ON `fiscalizepro`.`Anexo` (`analiseId` ASC);


-- -----------------------------------------------------
-- Table `fiscalizepro`.`Dossie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalizepro`.`Dossie` (
  `dossieId` INT NOT NULL AUTO_INCREMENT,
  `usuarioCriacaoId` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(4000) NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataAtualizacao` DATETIME NOT NULL,
  PRIMARY KEY (`dossieId`),
  CONSTRAINT `fk_Dossie_Usuario1`
    FOREIGN KEY (`usuarioCriacaoId`)
    REFERENCES `fiscalizepro`.`Usuario` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Dossie_Usuario1_idx` ON `fiscalizepro`.`Dossie` (`usuarioCriacaoId` ASC);


-- -----------------------------------------------------
-- Table `fiscalizepro`.`AnaliseDossie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fiscalizepro`.`AnaliseDossie` (
  `analiseDossieId` INT NOT NULL AUTO_INCREMENT,
  `usuarioAdicionouId` INT NOT NULL,
  `dossieId` INT NOT NULL,
  `analiseId` INT NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  PRIMARY KEY (`analiseDossieId`),
  CONSTRAINT `fk_Dossie_has_Analise_Dossie1`
    FOREIGN KEY (`dossieId`)
    REFERENCES `fiscalizepro`.`Dossie` (`dossieId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dossie_has_Analise_Analise1`
    FOREIGN KEY (`analiseId`)
    REFERENCES `fiscalizepro`.`Analise` (`analiseId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AnaliseDossie_Usuario1`
    FOREIGN KEY (`usuarioAdicionouId`)
    REFERENCES `fiscalizepro`.`Usuario` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Dossie_has_Analise_Analise1_idx` ON `fiscalizepro`.`AnaliseDossie` (`analiseId` ASC);

CREATE INDEX `fk_Dossie_has_Analise_Dossie1_idx` ON `fiscalizepro`.`AnaliseDossie` (`dossieId` ASC);

CREATE INDEX `fk_AnaliseDossie_Usuario1_idx` ON `fiscalizepro`.`AnaliseDossie` (`usuarioAdicionouId` ASC);

CREATE USER 'fiscalizepro' IDENTIFIED BY 'fiscalizepro';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
